apiVersion: v2
name: spsh-client
description: Helm-Chart f√ºr den Schulportal-SH Client
type: application
version: 0.1.1
appVersion: "latest" # (see :https://github.com/dBildungsplattform/schulportal-client/pkgs/container/schulportal-client)
